# Generated by Django 3.2 on 2021-04-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ydt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='body',
        ),
    ]
