# Generated by Django 3.2 on 2021-04-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ydt', '0002_rename_description_todo_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='body',
            new_name='description',
        ),
    ]
