# Generated by Django 3.2 on 2021-04-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ydt', '0003_rename_body_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='responsible',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
